let api = {
    "login": "Vedantnawale",
    "id": 122304824,
    "node_id": "U_kgDOB0o5OA",
    "avatar_url": "https://avatars.githubusercontent.com/u/122304824?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Vedantnawale",
    "html_url": "https://github.com/Vedantnawale",
    "followers_url": "https://api.github.com/users/Vedantnawale/followers",
    "following_url": "https://api.github.com/users/Vedantnawale/following{/other_user}",
    "gists_url": "https://api.github.com/users/Vedantnawale/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Vedantnawale/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Vedantnawale/subscriptions",
    "organizations_url": "https://api.github.com/users/Vedantnawale/orgs",
    "repos_url": "https://api.github.com/users/Vedantnawale/repos",
    "events_url": "https://api.github.com/users/Vedantnawale/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Vedantnawale/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Vedant Nawale",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 37,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2023-01-09T17:42:18Z",
    "updated_at": "2023-10-30T08:13:34Z"
  }
  api.login = "vedant"
  console.log(api.login);